name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'
          channel: 'stable'

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Clean project
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get

      - name: Fix Missing Gradle Wrapper
        run: |
          cd android
          if [ ! -f "./gradlew" ]; then
            echo "Gradlew not found! Regenerating..."
            flutter pub run gradle wrapper
          fi
          chmod +x ./gradlew

      - name: Build APK
        run: flutter build apk
